### ISSUE TITLE
2. Haciendo foco en los estilos del pie de página (Footer)

### ISSUE THREAD

**Issue by Ivanram569** [BenRomeroArg/Mercado-Liebre#2]
¿El contenido de todos los artículos está centrado?
Si.
¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles?
El tamaño de letra hay que cambiar por el siguiente código:
```css
.element.style {
    font-size: 2em;
}
```
A cada <li> hay que agregarle el margin inferior de 10 px:
```css
.element.style{
   margin-bottom: 10px;
}
```
